wllnDcjvvMs@B	Light
yllnDujvvM~@Cr@C	Light
wnknDqlvvMbCG	Light
kgknDc|pvM_AK	Light
uoknD{}pvMaE]uHm@	Light
k_lnDw`qvMrHl@|D\	Light
g}hnDiqvvMeBD	Light
__kmDmffvM?oB_@kBSYkAiBgAwB	Hard
gekmDeufvMIQ	Light
c_kmDccfvMBiB?W	Hard
kwlmDacgvM~@S	Light
qzlmDgcgvMVA	Light
uikmDsdpvMk@UsCyD	Light
uokmDckpvMWa@	Light
m}kmDwwjvMYM	Hard
g~kmDexjvMi@W	Light
aammDotrvMdBpB	Hard
ydlmDanqvMj@bAfD`GjAvBf@VjEdI^n@^n@ZNr@?	Hard
oyjmDgacvMoBK	Light
kslmDiccvMI?	Hard
}qlmDma`vMa@eAa@aAQg@i@kA	Light
gplmDo}_vMu@}B	Hard
mdlmDgc_vMwEaNGSuCgI	Hard
i~jmDicfvMQbFOlHErBQtIJ|D	Light
wxjmDefivMMlGEbCIrE	Light
ojkmD_njvMp@X	Light
{rjmDcbjvMeAB	Light
injmDwajvMi@MeA?a@@	Hard
qrmmDkcovM|@{@NK	Light
gtmmDyaovMt@q@	Hard
ozkmDygpvMeAt@	Hard
u|kmDcfpvMg@^	Light
i~kmDqepvMJIjAy@	Light
y~kmDgepvMNI	Hard
ummmDueovMw@FUH	Light
sslmDscrvMjCdD	Light
golmDm~qvMlBfD	Hard
owlmD_n`vMZv@	Light
kylmD_r`vMz@~B	Hard
ejkmDyoxuMuFgK	Light
{qkmDa|xuMyBgE	Hard
olgmDgxxvMsEpCgAn@gAl@	Light
s}gmDylxvMmEdC	Light
shemD_gbvMk@|A	Hard
uqimD_bwvMn@{@	Light
{kfmDs`zvMq@O	Hard
ggdmDssuvMAr@Lj@	Hard
_jhmDij`vMC^U\	Light
cjemDkkkvMsAJm@^	Light
usemDoikvMhBqBNq@	Light
yefmDsmevMlAO	Light
k_fmDysevMiAfE	Light
c}emDavfvMVML@PN	Light
uajmDksqvMbBeA	Hard
i{fmDeepvMa@{A	Light
mfgmDmpnvMpDuA	Light
k}fmDmiqvMaA`@	Light
eyhmDmvlvMh@kALS	Light
iudmDkkkvMsNG	Hard
widmDgkkvMqJC	Light
osemDohkvMq@V	Light
}ncmDi{svMgBkEEMwBoF	Light
asfmDopovMSs@	Light
ahimD}ctvMYE	Light
yhimDkgtvMAfB	Light
_vemD}pivM^wB	Hard
_uemDutivMPgH	Light
etemDiajvMBi@JmDFuA	Hard
ijhmD{{rvMPMtBuAbAs@	Light
}chmDs`svMhFoD	Hard
unimD{uuvMo@cBu@o@	Light
{qimDozuvMWU	Hard
m`jmDyjvvMf@~@	Hard
e_jmDyhvvMZ^PT	Light
oobmDunpvMIh@Il@Mp@AbB	Light
k}dmDocrvMEK	Hard
{dfmD}sqvMpBk@	Light
iafmDiuqvMrBm@	Hard
i}emD{vqvMBLRbA	Hard
yydmDicqvMn@R	Hard
{rdmDs`qvMHBxA`@b@L	Hard
{ddmD{zpvMyCy@_D{@wAa@g@O	Light
yddmDg{pvMHB	Hard
addmD_{pvMfAZ	Light
uscmDmtpvMkBi@w@So@SIC	Light
exbmDsipvMu@U	Hard
wadmDuypvMa@K	Light
ixdmDubqvMx@TbAX	Light
ktdmDeaqvMn@P	Hard
_sdmDe`qvMkDcA	Light
_mdmDk~pvM|@V	Light
}hdmDy|pvM|Ab@	Hard
{}cmDwxpvMjBf@fOfE	Light
gjcmDgqpvMpBj@	Hard
yfcmDmopvMqBk@o@Q	Light
wacmDiasvMPKfBeA	Hard
kacmDo`svMKY	Light
wobmDkfpvM]KUG	Hard
q{cmDuqrvMNIl@O	Light
{jfmDq}nvMu@\	Hard
ufcmD{opvMpF|AjDdA	Light
}rhmD}|lvMcCzB	Light
awhmDaylvMMRa@~@	Light
mpimD_eovMi@rB	Light
wqimDkaovMa@t@	Hard
ioimD{mpvMB`G	Hard
yqcmDoadvMWQQO	Light
crcmDubdvM`@b@`AjApEjI	Light
gqcmD}ddvMDjB	Hard
addmDcndvMgEsAe@QaBq@KGqAk@	Hard
okdmDiqdvM{@@aAR	Light
asemDunjvMNqB	Hard
qremDgrjvMIaAJaC	Light
msemDwjjvMDmA	Light
gsemDemjvMDo@	Hard
}y`mDirovMoMiD	Hard
iddmDakkvMmDE	Hard
q~cmDyjkvMeCEq@A	Light
w_dmDkkkvM`CA\A	Hard
o|imDc}bvMmBS	Hard
s~kmDov~uMkBoF	Light
_blmD_~~uMmAgD	Hard
_|imDqdavMfA|A	Hard
mtjmDagxuM_AEiDCkBU_Bc@kB_AuAkA_AgA	Hard
o{dmDiexuMKV	Hard
yremDqhwuMr@c@	Hard
eqemDuiwuMl@q@	Light
}udmDmcyuM{@~Dk@nEObC	Light
ynbmDurpvMl@uD	Hard
uqbmDcgpvMa@M	Light
kmbmDkxpvMTcB	Light
}jbmDqaqvMg@vD	Light
_fdmDu{pvMd@L	Light
ybdmDazpvMw@U	Hard
ytemDm|xvMu@qC	Light
ovemD_ayvMk@}B	Hard
o_fmD}qyvM_@e@	Hard
o`fmDcsyvMo@y@	Light
{wemD}dyvMa@wAgAqCiAeBaAqA	Light
s`jmDmjvvMQ]AKKuBDcBxDaI	Light
k|hmDanfvM_BOKA}AO	Hard
k{hmD{mfvM_@E	Light
k{dmDeydvMYKiAm@	Light
o~dmD_{dvMeBs@	Hard
a`fmD{jevM^P~Al@d@Rd@P	Light
}yemD}fevMsDsAcBo@o@a@	Light
ewemDseevMwAi@	Hard
yagmDsyevMcGwA	Light
_ogmD{~evM|C~@HB	Light
i_fmDizfvMlAK	Hard
{xemDw|fvMcAhA	Light
i|fmDuagvMeAUMEi@M	Hard
iahmDww`vMg@|@	Light
i~hmDen_vM`@b@	Light
cwgmDgk~uMH_A[q@UQo@S	Light
eldmDkzfvMKK	Light
oiemDukgvMo@K	Light
gmemD_jgvMLe@	Light
w}gmDqqgvMWYQO	Hard
uuhmDwlfvMy@K	Light
{whmDe}_vM`Ap@f@d@	Light
awcmD_{evMMaA	Hard
uvcmDmyevMKq@	Light
iifmDo}yvMQSQy@Ps@zBsC	Light
o`fmD_mzvMjBuD	Hard
c|emDctzvMEV	Light
irgmDerwuMg@_@kAu@gCcAeSiFcRiDob@oA	Hard
mnimD_zuuMd@Z	Light
gnjmDq|vuM[o@Ui@	Light
yojmDk_wuMKUu@gC	Hard
yojmDk_wuMoArA	Hard
kqjmDiewuM|@zCHTUJ	Light
kljmDu`wuMwA\	Hard
uhlmDkctuMUG	Hard
u{kmD}uuuMeGm@	Light
{qjmDidwuM}AwE	Light
kljmDoawuMrBNlHtB`B`@vHvBb@JhABrA[`@[dAyA	Light
yefmDsmevMz@Zt@V	Hard
gbfmD_levMdAb@	Light
crjmDcgwuMVx@n@pAXXtAL	Light
mojmDm`wuMz@Yd@G	Hard
glemD_aevM~Cx@	Light
ehemDo_evM\HtCv@	Light
_bfmDmbwuMiA\	Light
udfmDyawuMjA_@	Light
sremDahwuMk@RyBl@	Light
ydemDowwuMHQb@s@Ra@	Light
czdmD{rxuMNcC	Hard
sydmD_wxuM\{C	Light
ocjmDo{nvMw@F	Hard
icjmDqblvMMtE	Light
wcjmD{{kvMCh@	Hard
gwemD_bivM@k@d@qL	Hard
{`cmDoxgvMl@fCHT	Hard
c_cmDqsgvMDLt@~C	Light
yybmDsjfvM@l@	Light
{fbmDeecvM`CG	Hard
ybbmDmecvMhAe@b@_@	Light
}sbmDudcvMNOPI|B@	Light
gqcmD}ddvM[fA	Hard
apcmD{idvMe@|C	Light
qsbmDedcvMMFqAzAq@v@KLOO	Hard
kzbmDkacvMv@p@	Hard
coamDsacvMkCGyAWqFcA	Light
wacmDw_hvMc@JKBCKJCZG	Light
_jcmDo|hvMg@mD	Hard
axcmDujkvMaAAQ?	Light
mzcmDsgkvMEy@	Hard
m_bmDsecvMZ@XB	Light
q}amDifcvMEZCT	Hard
u~amDydcvMsBC	Light
ybbmDmecvMvAC	Hard
q~amDqecvMHc@	Light
u|amDyicvM[rB	Light
k`bmDw|jvMk@SICeA]	Light
exbmDo_ruMqYeQkAaAq@w@	Hard
y{cmD}}ruMuE}K	Light
{icmDg`evMVN	Hard
i|lmD}|gvMCU	Hard
e}lmDmugvMZoF	Light
c}lmD{pgvMAbA?d@	Light
}{fmD}iuuMe@bB	Hard
q|imDm{vuM_Be@kBg@qAIkD}@g@EMBSRG\VxA	Light
}bjmD{}vuM_FuAmAC	Light
wbhmDgivuMHQJqA	Light
yybmDeo{uMcEfJkAvB	Light
_`dmD{{yuMe@b@	Light
abbmDyo|uMsBhBGF	Light
{kbmDye|uM\e@	Light
o{amDo}~uMCN	Hard
gkamD_a}uMzHoD`@SNu@	Hard
_`mmDu_jvMp@D	Light
czamDgjhvMu@@	Hard
mqamDqhhvMeAO	Light
slgmDmravMo@g@	Hard
opfmDwjvuMQd@	Light
kmgmD_hgvMpM`D	Hard
owhmDcmfvM{BW	Hard
ubimDcofvMsGm@	Hard
ikimDqpfvMmAE	Light
{bjmDg~bvMeBM	Light
afjmDu~bvMoCS	Hard
kdgmDemuuMpAVpCx@	Light
c{fmDubxuMt@F	Hard
czkmD}zpvM{@_BIu@Uc@aAeB	Light
uphmDkkhvMV`@	Light
imhmDalhvM[ZQP[X	Hard
g}hmDam_vMr@|@	Hard
sckmDyexuM_@wA?i@R]u@Tc@G	Light
ooimDewvuMw@Cm@M	Light
e_fmD}_avMqA`D	Light
edfmDq|`vMbAl@HF	Hard
urimDwwvuM{HuB	Light
gxdmD}luvMWL	Light
eqfmD}fvuM]?	Hard
cvemDmgivMEdA	Light
qaemD}|dvMXL	Light
kodmD}sdvMRJJDbBr@	Light
mbcmDu}gvMXxA	Light
sacmD{zgvMVjA	Hard
g_jmDuskvMgA_@	Hard
oelmDanqvMMU	Light
}_jmDw}bvM}AO	Light
{`kmDkydvMAaA	Light
sojmDg{kvMbE\	Light
w_emDoiuvMe@X	Light
_}cmDwjkvMo@A	Light
ckimDeybvMyA]	Hard
arimD_|bvMET	Light
ckemDsbbvMXq@l@_B	Light
erdmDekdvMfB}F	Light
oqdmDotdvM{HuC	Light
cfjmDioavMt@h@rApA	Light
kvjmDy~ivMDaA	Light
gmdmDgwuvMV@P`@Ed@	Light
emgmDibbvMx@h@pA~@	Hard
kkgmD_abvMr@Nx@A	Light
cokmD{ojvMk@W	Light
}|jmDkscvMIlFc@~Hu@xN	Light
y`emDq|dvM~BbAlAl@`Bd@	Hard
yycmDoqtvMlApC	Hard
wihmDyifvMk@Oa@M	Light
i`fmD_ckvMpCgA	Light
imhmD}kfvMV@N@X@	Light
kukmDuuuuM}@Mc@i@	Light
cyemDiduuMVeAl@RZJ	Light
agkmDmvpvMq@`@w@l@	Light
eehmD}ywuMwFwAwA]kQ_Dw`@mA	Hard
c{gmDcaavMaCdE	Light
gtkmD}}xuMoBaE	Light
alkmDmqxuMWc@	Light
mjjmDs_jvM{BcA	Hard
yljmD_tjvMdAoDv@oCb@mBXeE	Light
}}kmDcepvMSL	Hard
cxkmDsipvMWPm@b@	Hard
wccmDqb{uM^A	Light
okdmDgryuMfGeF	Light
_`dmDsu{uMwAaA	Hard
wbdmDuw{uMe@Y	Light
onbmDqa|uMmAfB	Light
}hbmDeecvM`@?	Light
{ecmDypcvMtEjI	Light
ezbmDwgfvM@_@?O	Light
wacmDw_hvMc@J	Light
}jjmDilovMn@z@	Hard
ofjmDiunvMCu@	Hard
y~amDihcvMn@}@	Light
alcmDwydvMtAqD	Light
u}mmDyszuMtEx@	Hard
_wmmD_rzuMh@L	Light
ahfmD{nevMz@`@	Hard
ynimDoqfvM|@JH@	Light
soimD{pfvMeDYqAC	Light
g}jmDg}cvMJhF	Light
e_mmDsi`vM~BkA	Light
eejmDcnavMeAs@	Light
{yimD}qfvMu@A	Light
kbjmDyrfvMN?HVIJQ?	Light
mtemD}}ivMFkB	Hard
anfmDy`zvMo@p@	Hard
qofmDg_zvMn@q@	Light
glimDirwvMIjAKhA	Light
erimDo~vvMMR	Light
gzgmDmoxvMnAs@dAm@fAo@	Light
grimD_|uvMl@n@	Light
iebmDq_kvMlBp@	Hard
uebmDccpvMfEhA	Light
mqbmDihpvMPeA	Hard
iummDi`ovMuAjA	Hard
idcmDmgsvMd@fA	Hard
c}emDurzvMJ_@	Light
_ydmDoluvMyBdA	Light
y|dmDijuvM{@b@	Hard
u~dmDeiuvMKD{@H}@j@	Hard
{bemDiguvMgCzA	Light
iydmDcmuvMsAp@M?	Light
cdjmD_mnvMDvA	Hard
oummDu`ovMf@c@	Light
o_fmDycwuMhBg@	Light
usgmDgxruMZ]f@C\PDl@	Light
ykjmDmavuM?e@	Light
_clmDe_zuMKSQqD	Light
qvbmD_u{uMWj@	Light
gikmDuljvMa@Q	Light
m{lmDmlgvMy@N	Light
{{cmDmidvMkBuAgBk@	Light
k}emDetzvMo@g@	Light
szgmDevwuMqIwB	Light
ozcmDowpvMCJ	Hard
w`cmD_qevM^_A	Hard
uacmD}ygvMq@iD	Hard
gkcmD}aivMQkA	Light
swcmDw~evMFZ	Hard
icemDyxwuMU`@	Light
i|emDkszvMIb@	Hard
m{bmDuhkvMdBd@	Hard
srmmDwpzuMpQxC	Light
y}lmDalgvM@i@	Light
c}fmDyfuuMQn@	Light
u}fmDieuuMe@fBy@~F	Hard
{kgmDgzsuMx@eF	Light
}`gmD{xtuMaC~P	Light
izkmD}gpvM_@V	Hard
_}jmDsacvMWA	Hard
}nfmDsjvuMRtA	Light
mvemDycivMIhB	Light
wvemDo`ivMC^	Hard
cscmDsdtvMb@fA	Hard
ctcmDqddvMl@h@	Light
qtgmDqbnvMrAqD	Hard
obdmDomdvMo@S	Hard
}cfmDwlevMGR	Light
q_}mD}t{uMzA~Dn@|B	Light
ka~mDi|xuMiBbC	Hard
}}}mDaayuMW`@	Light
s`~mDcb~uMvAf@\QHBR^	Light
a|}mDu_~uMON[@	Hard
_~}mDa`~uMBY	Hard
ijanD_yvuMNqD	Light
yianDq~vuMH{B	Light
mianDacwuMJeD	Light
ifanDcfxuMCbBGhB	Hard
ufanDu_xuMKhC	Light
wlenDkpyuMRR	Light
clenDwoyuMr@v@	Hard
mrgnDogtuMkAhBaBpC	Light
exgnD{_tuMlD}F	Light
wfgnDaytuMLHGJoBvC	Light
mbgnDk~tuMk@|@oAtB	Hard
m}fnDofuuMfAkB	Hard
idfnDwivuMkAlB	Hard
uffnDifvuMW`@	Light
ubfnDclvuMs@jA	Light
stenDe`wuM{@tA	Hard
ovenDo}vuM{C~E	Light
qucnDkkzuMdA}C	Light
}pcnDovzuMbCyK	Light
_lcnDwe{uMXoA	Light
qihnDcfsuMu@jA	Hard
gkhnDwcsuMKP	Light
s{anDgwuuMAL	Hard
i~_nDgituMAV	Light
_~_nDyktuMIpA	Hard
ardnD}qxuMGH}AhC	Hard
wldnDoyxuMiDpF	Light
kscnDipzuMn@mBXkA	Light
qeanDwuxuMCpA?J	Light
ekcnDgh{uMTcAPq@	Light
ouenD_axuM_@[yBkB	Light
_~cnD}uyuMk@fB	Light
ivdnDukxuMgC`E	Hard
oefnDcivuMhAmB	Hard
cmdnD}vfvMuAg@	Hard
co}mD{fkvMdBgB	Light
qh~mDclkvMaAAqA`@_AZo@|@K^Ap@	Light
e||mD_slvM_AqA	Hard
_}`nDqfzuMmD{FS]KO	Light
{renD}bavMqCtB	Light
o{enDu|`vMQJ	Hard
c`fnDsy`vMMh@]^]\	Light
y``nD}}evMKY	Hard
eb`nDoafvM^vAJX	Light
u|`nD}{dvMR^	Light
a|`nD}zdvMZHv@A	Hard
ey`nDmzdvMUn@Cj@	Light
itenDsbbvM]dB	Hard
u}enDidavMEz@^r@b@d@	Light
{_fnD{}`vMP}@\[n@C	Light
w{enDs_avMPR	Hard
wbfnDyx`vM`@e@VK	Light
wl`nDw}cvMo@Ac@Qe@i@	Light
}b`nDq}bvMbAR	Light
{slnDyudvMnAD	Light
coknDordvMlA@	Light
cg}mDerfvMxBt@	Light
ic}mDopfvMTL	Light
sb}mDapfvMFb@	Hard
gm~mDgc~uMKeA[u@	Hard
uhknDksdvMr@M	Hard
agknDysdvM~Ba@	Light
gw~mDcq~uMtAdA	Light
olfnDak`vMaAE	Hard
y`fnDwa`vMa@CuHgG	Light
mk_nDsakvMuGhAaD^aAJqIbA	Hard
k{bnDwvfvMm@Uw@W	Light
sg~mDaxivM^gB	Light
ye`nDy{jvMyBR	Light
y`_nDmdkvMsIxA	Light
sgcnDqphvMSIOE	Hard
s|cnDww|uMOfBJx@Td@	Light
ofanDuwzuMKX_@D	Light
ayfnDmb{uMc@_A	Light
umfnDao`vMh@p@	Hard
_o}mD}l`vMyBlF	Light
yk_nD_lyuMmBe@	Light
on~mDcg~uM_Bu@	Light
ef~mDisxuMo@w@KMc@i@wAiBEa@	Light
uh~mD}xxuMJL`@Cx@e@	Light
yc~mDisxuMtCpDl@t@	Light
g_knDax|uMvAu@xA_@dCiBfCeB	Light
wbgnDe{_vMhBaB	Light
arknDsc}uMrAtEnBvE|BrE	Light
_yhnDwj~uMs@h@	Light
aggnDq{{uMNX	Hard
qfgnDwz{uMbAzB	Light
qlhnDyc}uMk@WKG	Hard
inhnDyd}uMa@Wu@e@Ue@	Light
itfnDyx~uMtHeF	Hard
_bgnDor{uMv@`BFL	Light
{dfnDuu~uMm@qA	Light
iafnDow~uM}A~@	Hard
gdfnDou~uMKF	Hard
}q~mDyayuMt@l@	Light
mfenD}h_vMDLr@bC	Light
qdgnDggavMd@PbCx@|BhAt@b@	Hard
syfnDmaavMTPRP	Light
krdnD{|avMgAt@	Light
s|dnD{ddvMDS	Hard
_lcnDo`avMzFrD	Light
wmbnDoj`vM{A}@yCiB	Light
ghanDab~uMGWYsA	Hard
u|`nDug~uMuFtBiBt@	Light
qp`nDu_dvMQo@?}@Ng@j@o@	Light
c}anDchfvMrAf@	Light
u}anDihfvMPD	Hard
i`anDoaevMrBpD	Hard
c|`nDkzdvM[k@y@wA	Light
a_anDmvdvMlA}@	Hard
yebnDke`vMx@h@	Hard
uc`nDgzbvM^a@	Light
ub`nDi{bvMPQ	Hard
sk~mDwwavM_Bm@	Light
_w~mDe~avMlB|@	Hard
qy_nD}_cvMpBz@	Hard
iebnD_iivM_EV	Hard
o`_nDaejvMqB`@_AH	Light
iffnD_ljvMM?S@	Hard
w`fnDk}ivMQI	Light
es`nDaujvM`@_@z@mADs@	Hard
qi`nDe{jvM}@H_CT	Hard
ap`nDczjvMqBD	Light
e|`nDepivMbA]	Light
az`nDcqivMNI	Light
gk~mDanjvMT~@f@dCrAzH	Hard
s}}mDushvMEy@	Light
q`~mD}chvMjAgK	Light
sa~mDghivMUqA	Hard
sx|mDqtivMI`B	Light
it|mDuilvMCfC	Hard
cf}mDw_hvMJ}@	Light
we}mDuahvMHoA	Hard
ah}mDmhgvMNm@ZkD	Light
u{~mD{ekvMcDl@	Light
m{~mD{n|uMu@`H	Hard
qm|mDoncvMaB`H[nA	Hard
mi}mDirfvMYYcCw@	Light
_c_nDyk_vMHwA\gBn@iBRm@	Light
a__nDgv_vMQn@i@~A	Light
ua_nDwd_vMUF	Hard
_b_nDqe_vMHX	Light
ua_nDwd_vMvAjE	Light
mtfnDkpjvM\fALh@	Light
atfnDgnjvMW_AMaB	Light
atbnDesfvMqCgAi@U	Light
m}cnDkxfvMqA~E	Light
{adnDuqfvMoAe@	Hard
kddnD{rfvMiBs@	Light
ardnDuyfvMjAb@	Light
cnfnD{efvMEmCCyB	Light
cnfnDmpfvM@hA	Light
ehfnDgygvMIE	Light
qhgnDy|evMhBI	Light
cignDw|evMPA	Hard
uqfnD__fvM~BG	Hard
gvgnDcxevMt@k@	Hard
etgnD}yevMxAq@~BY	Light
c}inDsvdvM|AL	Hard
ezinDuudvM_B?_AR	Light
cjhnD{hevMx@m@	Hard
ihhnDijevM`H}E	Light
asenDyuivMgAc@	Light
mdcnDg}hvMDS	Light
cecnDuzhvMTqA	Hard
ih~mDoxxuMh@l@TV	Light
}_~mDe|fvMp@PJD	Light
kz}mDgyfvMyBu@IC	Hard
_~}mDm{fvMtBr@	Hard
ubknDor|uMgAp@	Light
y`hnDw~|uMiCy@	Light
wygnDu{|uMs@Y	Hard
gh_nDujyuMa@Ze@EWY	Light
svknDmf|uM{AJ	Light
u`~mDyeivM|@bG	Hard
w~}mDu}hvMHf@	Light
uw}mDy}jvMw@f@	Hard
au|mDmpjvMAf@	Light
oc~mD{|fvMa@O	Light
qd~mDk}fvMAy@L_B	Hard
sr_nDe{bvMaBy@SK	Hard
gi~mDoqcvMDU	Hard
ob`nDa}ivMe@H	Hard
uc`nDw|ivM}@T	Light
oq|mDcv{vMIjEEjB	Hard
wu|mDgjyvMAW	Hard
cv|mDwp|vM}HM{Ek@kDw@c@OOEOEKC	Light
yr|mD_k{vM@UDkB	Light
ei}mDurwuMNP	Light
ek}mD}uwuMNPrDvETZ	Light
e~}mDqkxuM`@b@	Light
wq|mDcjyvMoBC	Hard
sm_nDg`_vMpE{A	Light
iu|mDysjvMBqC	Hard
eu|mDkxjvMCyF	Light
c`bnDg{tuMJuA	Hard
aq|mDwj|vM?[	Light
}p|mDqm|vMBw@	Light
w_`nDw}ivMQBeAP	Light
ghcnD{phvMgA`E	Light
ojcnDyjhvM]rA	Hard
kcenDkojvMj@@	Hard
_benDiojvMX@	Light
qw`nDgfbvMjBq@	Light
ktenDwayuM_@`@	Light
olbnDoi`vMg@_@	Light
ybenDmowuM{AyA	Light
__cnDudivM|@o@	Hard
qshnDqp~uMfEsD	Light
imhnDev~uMb@_@	Hard
y}}mDouhvMCs@	Hard
et|mDstzuMi@kA	Hard
yi~mDmh~uMPf@	Light
i||mDql{uMOo@	Light
yw~mDsp~uMeA}BWe@	Light
{hgnDy~{uMx@fB	Hard
ywenD}~`vMw@f@	Light
}bfnD{lvuMzAaC	Light
u{enDgwvuMtCwE	Light
e_~mDwhivMo@|A	Light
{a~mD{jivMRnA	Hard
{acnDmaivMYd@e@pA	Hard
em}mDqu|vMPD	Hard
sl}mDku|vM|Ad@	Light
af_nDucjvMSEyA@	Hard
qu~mDcb}vMw@Q	Light
yp}mDyv|vMdAV	Light
qm}mDsmyuMh@]	Light
{g}mDsqyuMv@g@fAs@	Light
kgfnD}kjvMoBJ	Hard
{jfnDqkjvMcAB}AX	Light
qqcnDwwgvMk@dB	Light
cadnDonfvMoClK	Light
yndnDibfvM`Gv@Vw@vCcL	Hard
sfcnDmvhvMf@sB	Light
kecnDazhvMFS	Hard
y|cnDazfvMEL	Light
_}cnDsyfvMMf@	Light
ycdnDasfvM\Ll@R	Hard
yxgnDaravMd@R|KdF	Hard
ujgnDgjavMjAf@	Hard
ikgnDkiavMiBy@	Light
y`inDue~uMbAq@	Hard
omjnDcd}uMjBqAp@e@	Light
qvhnDwm~uM~AyA	Light
oz`nDgsivM\x@	Light
{b}mDismvMTwAt@u@	Light
spdnDo_wvMk@Zu@jA	Light
usdnDg|vvMq@xKSl@	Light
uz}mD_lovMcAK	Light
sy~mDaorvM~@nLZrBv@xC	Light
iz~mD}srvMDZ@XLdB	Hard
a{~mDasrvM}AcV	Light
_u~mDcyqvMJf@^jBNbBDpB	Light
u~~mDunsvMWyCMmAYwCMsA	Light
}x_nDuw{vM@nAJpK	Light
ox_nDsh{vM@pA	Hard
mv_nDyoxvMDoD	Hard
gednDknzvMjAuK	Light
}fdnDuczvMT{C	Hard
g~dnDeysvMLiCFiAFiA	Light
_benDo`rvMM`D	Light
kcenDmpqvMMzDG`BIfCE~A	Light
e~cnDiu{vMP@|Gt@	Light
u}cnDoy{vM@fC	Hard
}xanDmu~vMo@P	Light
wubnDqptvMFY	Light
msbnDqutvMW~@	Hard
kobnDkazvM?K	Light
_o~mDa}tvM{@L	Light
_}~mDmztvMfAMzAU	Light
wscnDe_uvMwAm@	Light
adcnDawtvMe@S	Light
_vbnD}otvMw@[	Light
mdbnDsftvMgB}@k@Wc@SeAg@qBw@	Light
syanDo`tvMg@U	Light
uvanD{~svMi@U	Light
uranDw|svMSG	Light
moanDi{svMg@O	Light
cy`nDsrsvMUI	Hard
gt`nDcpsvMo@YoAg@[M	Light
ih`nDyisvMwB_Au@[o@YYMYMk@UYMQISI	Light
i}_nD}csvMk@UOIg@W_@Qa@Sc@Qa@Ok@U	Hard
af`nDshsvMUKWK	Light
wd_nDawrvMSIQG	Hard
}e_nDswrvM_A_@	Light
spdnDo_wvMuAB	Hard
isdnDk_wvMY@	Light
gsdnD{_wvMAN	Hard
{tdnDy_wvMX?	Light
{vdnDu_wvM~@C	Hard
ktbnDyawvM~AAd@?	Hard
epbnD{awvMvCC	Light
mkbnDmawvMwCB	Light
uw~mDc~ovM}@C	Light
i{anDqvovMlDm@	Hard
mbbnDytovMjB[vB[AP	Light
_zbnD_wovMtBNbEZhAL	Light
wjcnDiyovMt@DpAH	Light
cvcnDwzovMx@FlAF	Hard
{qcnDgzovMrBN	Light
scdnDw|ovMjAJtCT`@B`@B	Light
yidnDq}ovMb@Df@Br@D	Light
kbenD_apvMt@Ff@FhAHx@Fl@B	Light
}eenDqapvMb@DZBH@f@D	Light
mienD{bpvMF\|@F	Hard
ggenDuapvMh@B	Light
aqfnDggpvMrOhAfBLlEX	Light
uzhnDwqpvMjGf@bPjA	Light
oijnDsxpvM~BRVBzALt@Dz@HZB	Light
eienD}apvMFd@IjASXk@Rc@MW]VmAHo@	Hard
}`~mD}vovMu@_GWcB	Hard
uf_nDoapvMl@JbANL@	Light
{hdnD{tyvMBe@	Hard
iagnDcipvMiDUsKw@	Light
eb_nDcgtvMDXFd@	Hard
}c_nDkwrvM`Br@VL	Light
c`_nDiurvMnCt@	Hard
kubnDkptvMhHpC	Light
gecnDuwtvM{Am@	Light
wicnDkq{vM?JMPK?OO	Light
oy_nDkk}vM@P@v@B~@ZrA	Light
ox`nDgf~vMHCTJBV	Hard
kw`nDge~vMCHUJ	Light
uz~mDmztvMsAR	Light
wvenDucpvMp@Dh@D	Light
{senDicpvMrEXVERQd@MRDRRF\	Hard
erenDqbpvMq@E	Hard
wsenDwbpvMoHe@	Light
g}enD}cpvM{R{A	Hard
gq}mD_uuvMqChB	Light
gv}mDmruvMvCoB	Light
gnenDmxovMTmBDe@	Light
_vdnDwmuvMkAh@	Light
gr_nDuvvvMt@vE	Light
e`_nDwytvMdBU	Light
okjnDkxpvMcDWkAIuBQe@EsE[	Light
ctjnDazpvMd@DjAH	Light
{qenD}~vvMh@A	Hard
qpenD__wvMV?	Light
_genDu~vvMcEBuA?cDF	Light
{tdnDg_pvMz@?rBJx@PhAN	Light
qhcnDmxovMQAeJo@	Light
_xdnDwpuvM^n@`@X	Light
_vdnDwmuvMgAG	Hard
ey_nD_n{vMEeFCkA	Light
oy_nDix{vMAq@	Hard
cy_nDw{{vM@f@?TBbA	Light
w|dnDyhtvMHwABw@FeBDkA	Light
cjanDe{ovM|@MfFw@pI{A	Light
}panDiyovM`Eu@VE	Light
qp_nD}ovvMPfA	Hard
_q~mDylqvM_AM	Light
gd~mDc_pvM{@L	Light
mzcnDm{ovMhCT	Hard
qy_nDuf|vM?h@@ZJvG	Hard
g}dnDs_pvMiAIcCO	Light
ucenDm`pvMeAFo@R{@d@	Hard
{|`nDmtsvMuA]	Light
kw`nDge~vMPl@	Light
iuinDwupvM`AH	Light
ie_nDs`pvMmAO	Hard
if`nDqdpvMpEu@tBM`AF	Light
si`nDiksvMbBt@	Hard
of`nDsisvM~FhC	Light
sgdnDqzyvMCXIvA	Light
wjdnDw}ovMNB	Light
ewdnDm_pvM^Dh@?	Hard
gudnDe|vvMs@_B	Hard
ctdnDi_wvMY@}@@	Hard
m{dnDq_wvMpCC	Light
geenDa}pvMBaAFqCDwB	Light
sienDsepvMSzA	Hard
_nenD{_pvMi@s@s@Y	Light
}penDibpvMg@G	Hard
mrhnD}opvM{K_A	Light
ex_nD_d}vMCx@	Light
ihgnD_iavMpAd@d@P	Hard
w_~mDolxuMa@g@kAwA	Light
sd~mDgrxuMoA}A	Light
cg~mDgvxuM[?	Hard
_h~mDgvxuMeAqA}@kA	Light
yx}mDidxuM}@gA	Hard
}tenDi~vvMW?M?	Hard
yrhnD}qvvMi@@_@@	Light
cfknD_o|uMoAr@OJg@EmCfB	Light
u}anDihfvM{Ai@{@[	Light
go_nDw~~uMwCrA	Light
oyknDaf|uMsFh@{IzB	Light
w`lnDwe|uMx@G	Light
}dknD}p|uMs@b@{A~@	Light
uy_nDi_|vMGaD	Light
}y_nDme|vMCwD	Light
yrcnDodavM]S	Hard
qyenDu}`vM[N	Light
wplnDcudvMq@C	Hard
irlnDgudvMs@CmBI	Light
kwlnDuudvMmES	Light
kllnDutdvMWAi@C_@Ci@C	Light
e|knDwrdvMc@Ma@O	Hard
}~knDusdvM}@A	Light
coknD_rdvMiAEa@AeAC	Light
ebknDqtdvMYD_C^	Light
w~jnDiudvMmBV	Light
izjnD{vdvM`Eg@	Light
{`lnDwsdvMoAC	Hard
kclnD{sdvM{AG	Light
wv}mDeuevMW`Bi@hD	Light
{q}mDujfvMbA{EXoB	Light
u~~mDq|~uMyAsDSOqAW	Light
ud_nDmc_vMc@P	Hard
{rbnDghivMpDE	Light
wujnDwwavMm@jAER	Light
cs|mDmp|vM_BI	Light
uqinDyudvMhCD	Light
_u~mDowqvMEQWo@e@mA	Light
if}mDo~uvMzCuBdBuA	Light
eaenDgojvMtJ@xDH	Hard
aw}mDauovMj@W	Light
cy|mDmgvvMqClB	Hard
{y}mDknuvMi@j@	Hard
}idnDigyuMhArA	Light
{tdnDy~ovMcDKgBM	Light
{genDwojvMnCJ	Light
ak~mDu}ovMwDA	Light
sn}mDw`pvMZi@`As@	Hard
ut}mDgb`vM]t@	Light
ktfnDy|xuMxBvAXj@	Hard
wdjnD}zzuM|BjE	Light
yk_nD_lyuMC[Ho@	Hard
wh_nDcnyuMRb@	Light
ypenD_|wuM}BoBWo@	Hard
_wenD_~vuMNU	Light
qefnDuoxuMt@n@	Light
cjjnDkxdvMs@C	Light
o~jnDc{avMy@C	Light
a`knDa|avM|@B	Hard
ko|mDs{mvMXpA@p@	Light
scdnDkmjvMmCI	Light
kuenDu`yuMMR	Hard
cp}mD_z|uMM]	Light
qp}mD}z|uMUw@	Hard
}~_nDmdtuMC`@	Light
yv`nDoj~uMwBx@cA^	Hard
uh}mDcrwuMjB|B\L	Hard
et}mDq_xuMl@TxAhB	Light
gx}mDefyuM\S	Light
mq~mD_m~uMr@^	Light
un_nDioyuM`B\	Light
ahanD}|xuMQi@Oc@qAmD	Light
_ocnDczzuMi@|B	Hard
wz~mDwu~uM}@eB_AsB	Light
scenDygyuMaCl@	Hard
e|~mDiy~uMt@tA	Light
gz~mDcv~uMZp@	Light
{c_nDwd_vMd@O	Hard
ey_nDi~jvM{@UWW	Light
{c}mDwckvMByA	Light
yoenD__wvMtA?	Light
i}hnD{qvvMhEK	Light
qfenDmupvMFaA	Light
ifenDowpvM`@qD	Hard
}benDouqvMIrBCl@	Hard
mbenDm{qvMEjAIpB	Light
gncnDwyovMnBL	Light
ofcnDyxovMh@Dx@H	Light
chcnDcytvM_CcA	Hard
aa_nDeurvMkBu@	Light
slbnD_uovMzBL	Light
{uanDov~vMYH	Light
etbnDqstvMEPUx@	Light
oubnDkqtvMTy@FU	Hard
whdnDavyvMJ{AHkA	Light
gobnDk~yvMAeA	Hard
}|cnD_duvMcAa@	Light
{uanD_xovM|Ci@	Light
k`cnDm_~vMkAr@	Light
gx_nD}epvMrATxCf@fBX	Light
ys~mD}jqvM_@v@	Light
i}|mDcwpvMrB{A	Light
yl~mDqujvMLz@C~@	Hard
io|mDcp|vMK\	Light
mq|mDio|vME]	Light
}d~mDm||vMc@M	Light
oc~mD}{|vM]I	Light
yr|mDk|zvMGfB	Hard
ahlnDitdvMs@Ek@Ci@A	Light
c{knDqrdvMa@E	Hard
{b}mDglfvMW|B@bA	Light
}n}mDaufvMDS	Hard
wtgnDcs|uM_AqB	Light
}fdnDmfbvMwAdA	Light
uwinDwt}uMd@YLV	Light
gsanD_b_vM_@uA	Light
ma}mD_wlvMHgC	Light
e~|mDsvlvMHJpAnB	Light
evanDkdfvMoAe@	Hard
mbbnDojfvMz@Z	Light
w{enDk_fvM_B@	Light
}fdnDc`fvM_Gu@wC_@	Light
mtdnDocfvMrDd@	Light
yodnDexfvMkAc@	Light
sp`nD}gdvMS]	Light
}q`nD}idvMgB}C	Hard
oi_nDycjvMq@F	Light
m~}mDm|hvMf@rG	Hard
i{}mDu{ivMC]Ci@	Hard
m{}mDs|ivMB\	Light
q{}mD}}ivMBh@	Hard
oy`nD}udvMYk@	Hard
u`~mDsfgvMVlA	Light
u`~mDsfgvM\Ff@C	Light
gkenD__wvM|@AtBA	Light
oy_nDqw{vM?W	Light
k_`nD_oevMnCmB	Hard
mkinDqudvMh@_@dAwA	Hard
gqfnDajjvMa@N	Light
uo_nDqmhvM~@V	Hard
ip_nD}jhvMNIn@QLQ}@U	Light
}s_nDwihvMn@UbAO	Hard
iz}mDyyfvM~Af@	Light
}`fnDkz`vM`@qB	Light
yu}mDqk}uMNp@	Light
_n|mDeszuMP]	Light
mm|mDctzuMLUTg@	Light
uk|mDsrzuMIT	Light
_m|mD{uevMo@Ds@Z	Light
eienD}apvMFd@IjASX	Hard
{hanDcf~uMJh@	Hard
mjinDmwavMdL\	Light
aidnDeu|uMEMKI	Light
s|_nDa_jvMTE	Hard
mx_nDaf{vM?R	Light
evcnD_lgvMW|@	Light
kucnDmcgvMkBy@	Light
mclnDyd|uMbAU	Light
ew|mDywivMMN	Light
qngnDckavMoHgD	Light
mt`nDw`pvMnEq@lDu@	Light
cacnD_xovMdF^	Light
gclnDktdvMpCF	Light
wl`nDejgvMT`@	Hard
aaenDyxrvM@[	Light
qpinD{x}uMoD`C	Light
qufnDakjvMb@M	Hard
}gdnDy|ovM}@G	Hard
acknD{tdvMr@K	Hard
y{}mD}_jvMF~@	Light
ac`nDuefvMLnA	Hard
kd`nDqlfvMD\Hn@XlC	Light
wt_nDiihvMXM	Light
ai_nDg`fvMu@f@	Hard
uzbnDmvfvMHB	Hard
modnDatyuM@Y	Light
}n~mDodivM^s@	Light
{ebnDelfvMZL	Light
}t}mDg~evMGRMjA	Light
gcbnDer~vMrHgC	Light
ccanD{{~vM~@vA	Light
syanDmv~vMnDm@	Hard
wccnDm~}vMo@q@	Light
}_}mDcw_wMMY	Hard
c}wmD{k~vMzD}APG	Hard
uyymDmt~vMeAyB	Light
{{ymDay~vMHN	Light
iczmDef_wMlFbL	Hard
uyymDmt~vM_ACMFSb@	Light
igzmDel_wMFG	Light
y`{mDow`wMEI	Light
yg{mDybawMw@uA	Hard
wd|mD}rbwMf@~@	Hard
oc|mD}pbwM^t@	Light
c}|mDk}cwMd@|@	Hard
krwmDup~vMeA^	Light
oq|mD{hcwMjAfC	Light
{y_nDmj}vMDlF	Light
yfdnDcc_wM{Dh@	Light
oz_nDka~vMBdC@`B	Light
uz_nDyh~vMBhC@`A	Light
uz_nDcl~vM?hB	Light
k~_nD}mawMCgBA_C	Light
y_`nDgccwM@|@DpBDdCDnC	Light
o``nDuncwM?d@FxBLlE	Light
{a`nDuedwMJpD@fAV|J	Light
gkbnD}kcwMAN	Light
mzcnD{s~vMr@}D	Hard
wednD}f}vMh@eD	Light
w{_nDmh_wMDrDBpCBlA	Light
{c`nDcdewMAi@	Light
u``nD}qcwM@p@Bt@	Light
e_`nDaubwMD~BDnD	Light
i{_nD{{~vM@ZDhD	Light
_{_nDkb~vMAcACsFAu@	Light
kgcnDyb~vMj@l@	Light
wecnDq`~vMy@{@	Hard
gcbnD_ggwMJX	Hard
{bbnDefgwMSX	Light
ug`nDgthwMb@At@Tl@V	Light
ivcnDsf_wMFu@eC`AwFz@	Light
{e`nDiofwMEaDAa@	Hard
_fcnDka~vMPRNN	Light
gb`nDgjdwMFLC`@FbB	Light
_d`nDwidwMFQXK	Hard
_{_nDca~vM?i@	Light
}}_nD}rawMAv@	Light
sdwmDas~vMg@qB	Light
oibnDuadwMKS	Light
y`cnDoxawMaAnE	Hard
}gbnDgbdwMGN]H	Light
ehbnDkcdwMHR	Light
qc`nDmeewMPjI	Light
ytcnD{m_wMHq@	Hard
se`nDmtfwMM@	Light
ugpmDgn~uM`DRz@GfA[	Light
mlpmDyr~uMtCt@	Light
ebqmDkcfvMBL@\I^	Light
}{omDmp~uMrAy@	Light
iyomDgr~uMdBeAbMcFdBqAfDkBb@Yl@]	Hard
o~omDwn~uMpAu@	Hard
}spmD}~}uMlAsAxB{AdNiI	Light
}`pmDqn~uMlBoATu@CyA	Light
gpomDg}~uMn@Fx@l@v@Rx@M|BsARC	Light
ecpmDo}cvMLPF`@	Light
uhqmDmhavMc@Iq@P	Light
mfqmDqlavMs@b@	Hard
ahqmDmkavMIT@dA	Light
uspmD}vbvMZN	Light
ytpmDusbvMMQE[B[LQJGXCZNNh@CTKPSL[?	Hard
olpmDotivMs@oA	Hard
{nrmD}ifvM{@eC	Light
c}nmD}wivMVC~@G|DY	Light
s}qmDkgivMd@_Ad@aA	Hard
qhtmD_ngvMS[	Light
gtqmDekgvMCT	Hard
oeumDgghvMRO	Light
{dumDwghvMd@@	Hard
gnpmD}igvMVJHR@RGP	Light
avsmDupjvMoAXaAv@	Light
{atmDadkvMKgBVeA	Hard
_dvmDetivMRg@?y@	Hard
g_vmDuvivMKL]v@Eh@	Light
istmDo{fvMWm@	Light
wpqmDsxivMCb@MN	Light
qvomDq`hvMYYa@_@	Light
ukpmD_bivMIQ@Y	Light
umpmDkggvMSDSCQY	Hard
gopmDmigvMLK	Hard
ybumD{ehvMIX	Hard
a`smDykgvMWi@	Light
ktqmDojgvMYf@	Light
{dtmDcpgvMAT	Hard
sbtmDcajvMLFNVBb@Sb@g@J	Light
acqmDqqhvMDa@	Light
gyrmDw|ivMGZUT	Light
ezrmDe{ivM_@B	Light
wzumDwjkvM?J	Hard
wzumDkjkvMMt@MN	Light
q~rmDiwjvMuAjC	Light
ayrmDy`kvMwAjCk@rA	Light
ikymDqthvMcCR	Light
iyxmDykkvMEbB	Hard
}lvmDk`nvMCy@	Light
amvmDebnvMGuC	Hard
ojvmDgemvMIUOi@CcA	Light
mmvmDwemvMrAE	Light
qkvmDormvMFhCJzD@\Rl@HT	Light
ozwmDeibvMGE	Light
wg{mD_qevM[U	Light
slzmD}}dvM{@o@GEo@c@[S	Hard
cpzmDa}dvMj@qA	Hard
oqymD_ecvMIiA	Light
}nymDosbvMG{@CS	Light
wdymDsp`vMFl@	Light
ssymDgwcvMPvB	Light
wgymDqdavML`B	Hard
igymDoaavMFn@	Light
agymD_`avM?J	Light
sgymDo_avMo@wI	Light
khymD}havMRjC	Light
qjymDmtavMEg@	Light
smymDojbvMc@iFCc@	Light
wpymDmccvMf@~FHjA	Light
urwmDkbcvMLSVIZF	Light
spwmDaccvMPR	Hard
y}wmDucbvMd@cAd@gATi@	Light
_zxmDmq`vM|@_B	Light
gsxmDq|`vM`@}@	Light
iexmDkvavMN]	Hard
ydxmDiwavMP_@P_@	Light
k`xmDi_bvM`@u@	Light
{~wmD{abvMP]N[	Light
awxmDiu`vMWb@_A`B	Light
k{wmDmgbvMi@lA	Light
u|wmD_ebvMO^	Hard
wixmDmmavMIRmBhE	Hard
omxmDofavMmBlE	Light
uowmDqacvMKd@	Light
ehqmD_lavM|@i@	Light
mfpmDmh_vMVn@x@lB	Light
iqpmD{|_vMnAtCP`@vDzI	Light
wrqmDq|avMFLdGxN	Light
ijqmDilavMXj@	Hard
murmD}ecvMhBhBhI~GpCrC	Light
wbrmDmtbvM`BpB~@nA	Light
ckqmDgiavMf@k@	Hard
_zzmDacfvMTCzBQ	Light
cazmDwdfvMBK	Hard
g_zmDwcfvMMLW@MG	Light
gtzmDocfvM_DX	Hard
u}ymDybfvMq@]	Hard
y_zmDqefvMT`@	Light
obymD_~evMhAwA	Light
ouxmDerfvMu@bB	Light
myxmDwlfvMtBuE	Light
wuxmDmsfvMVe@	Hard
krxmDyrfvM}@g@	Light
eqwmD{efvM?KJ[TOVAd@^Db@CNWTKDe@GGEMW	Light
m{ymDu_gvMl@mGx@}H	Light
_azmDcefvMXQ	Hard
c{ymDe_gvMMA	Hard
m}ymDytfvMRyBf@sE	Light
e`ymDw`fvMR[Zq@	Hard
_~xmDidfvMVL	Light
a`xmDqpevMrA|@	Light
kowmDugfvMd@^Db@	Light
{dvmDihfvMm@?c@Ma@a@	Light
{nymDa}ivMYr@	Hard
uoymDm{ivMe@tAk@b@	Light
ovymDwqivMB\	Light
grymDswivMyAZ	Hard
qbymD{gjvMcC_B	Light
ufymD{jjvMOJY@w@rB	Hard
cdymDwnkvMFK	Hard
}eymD}mjvMQb@	Hard
{`ymDqfjvMu@i@	Light
m{xmDmbjvMw@k@	Hard
kqxmDq{ivM|DjCp@b@z@h@	Light
ofymDyljvMFTCX	Hard
youmDiugvMRC^HTV	Light
mpumDeugvMPC	Light
uoumDepgvM]KW]	Light
{{vmDqqhvMqB~BcA|@x@~BjD~J	Light
g`wmDyghvMe@mAa@_@	Light
i_xmDumivMu@e@	Light
e`wmDkoivMd@X	Light
gawmDepivM`@X	Hard
kgwmDmrivM~A\lA`@	Hard
gawmDepivMP?	Hard
wlzmDe}lvMp@[LC	Hard
ktzmDowlvMrFuD	Light
ytzmDewlvMLI	Hard
uxxmDchnvMdC?	Hard
otxmDchnvMR?	Hard
{avmDsdmvM|CnB	Hard
}|umDcamvMjAv@VN	Light
o`tmDakkvMfAcCLUVg@Zs@	Hard
e|smDwrkvMp@sAf@oATo@	Light
ahvmDkemvM{@B	Hard
udtmDc`jvMTYPGX@	Light
q|tmDwyhvMDW`@w@	Light
owtmDyuhvMGDOF	Light
gxtmDkuhvMe@F	Hard
mytmDcuhvMs@S	Light
aeumDsdhvMQOCKCU	Light
mfvmDypfvMl@AZHh@`@	Light
c{tmD}ifvMCXKR	Light
}wtmDu|hvMVR	Light
ewtmDa|hvMVb@Jl@	Hard
uvtmD{}hvMOx@	Light
avtmDoyhvM?P	Hard
avtmD}xhvMCZ	Light
ctumDwdevMPYd@Mb@JTb@Ct@	Light
upumDybevMOR	Light
a{rmD{mcvMHG	Light
cyrmDyncvMi@b@Xp@	Light
cyrmDyncvMO`@?r@	Light
gurmDorcvMwBhB	Hard
apwmDmbcvMJZ	Hard
}vrmD}xlvMWhG	Light
gyrmD}ilvMy@fC	Light
{srmDy|lvM_BB	Light
{vrmDm}lvMrJS`@?	Light
wirmDq}lvMI@cAB	Hard
{cxmDgekvMbAB	Light
kaxmDsdkvMK?	Light
oyxmDuhkvM@ZCP	Hard
apumDghavMk@}@	Hard
gepmD}mfvMXeB	Hard
sepmD}zdvMNM	Light
o~mmDovcvMIX	Light
oanmD_xcvMLOZI	Light
elpmDsfcvM_@K	Light
obpmD{{cvMER	Light
wdpmDkzcvMOM	Light
q{omDqepvMaDt@	Light
sermDm|kvM|Au@	Light
ubrmDc~kvMr@]	Hard
chrmD_{kvMnAm@	Hard
cfsmDqojvM[AkFUcBC	Light
ifomDw{jvMZnB	Hard
qeomD}tjvMYg@gAa@	Light
s|nmDccnvMSJuMpI	Hard
eqomDyhmvMNdDb@|D@dA	Hard
eqomDwumvMVVFh@Ib@	Light
{somDaumvMJMNM	Hard
_somD}umvM^C	Light
asomDuqmvMSQ	Light
usomDgrmvMQk@	Hard
cyomDeomvMb@Y~@s@	Hard
czqmDo_lvMc@WyAA	Light
kjomDg{lvMk@A	Light
gvnmDufnvMIB	Hard
u{qmDcblvMNG	Hard
gbomDgwivMNAb@Cd@EhAI	Light
}kqmDchkvMk@kA	Hard
wuumDsamvMi@R	Hard
swtmDejtuMSY	Light
ovumD_juuMQO	Hard
awumDojuuMOM	Light
ywzmDoovuMRIzAg@nAa@	Light
oxqmD_gwuMeAvD	Hard
esqmDwtwuM{CtK	Light
aa{mDe{|uMSf@	Hard
khzmDmd~uMo@pA	Light
ckzmDy}yuMn@d@	Hard
kyxmDsoruMm@wB	Hard
iyxmDckzuM?t@^`A	Light
sgxmDqqwuMrA~@	Light
guvmDm{xuMmAo@	Light
ujrmDerruMEJ	Light
gntmDi}suMoBwC	Light
cexmDggwuMWw@	Light
waxmD{mwuMy@HyAV	Hard
w`rmDqsvuMdCoIDM	Light
qj|mDcczuMYm@	Hard
gc{mDskwuMBJTpA	Light
o~xmDa|ruMIYM[o@wB	Light
_bymDefsuMr@vB	Light
yktmD}ysuM}@uA	Light
aotmDc_tuMh@x@hA`B	Hard
k~zmD{n|uMqAoB	Light
}vxmDwezuM{BcB	Hard
agwmDmeyuM_Aa@	Hard
_zvmDe~xuMqAo@	Light
oevmDcrxuMXf@jAbF	Hard
ibvmDwixuMFX	Light
a~xmD_lzuMb@Z	Hard
}|xmDckzuMz@n@	Light
ge{mDiu|uM\q@	Light
kc{mD{v|uMMR	Light
}`{mDkr|uMy@mA	Light
id{mD{v|uMHU	Hard
_d{mDqw|uMlAaC	Light
yc{mDgv|uM}@hBWn@s@pA}@hB	Light
mbymDob`vMYa@	Hard
}`ymDwe`vMNT	Hard
kcymDkd`vMDU	Light
mcymDwa`vMo@x@	Hard
}dymD}_`vM{@xB	Light
gmzmDy}}uMzAsClGeM	Light
ahvmDetxuM{Ay@	Hard
g`ymDwmzuMdAv@	Light
gyzmDaslvMsA|@	Hard
{{zmDcqlvM{B|A	Light
u_|mDwkdvMr@eB	Hard
yf|mDs}cvMeBzD	Hard
yo{mD{ievMu@`B	Light
ks{mDucevMkDdJ	Light
k_{mDyafvMiCZ	Light
ak{mD{sevMnE{K	Light
cd{mDy`fvMM@	Light
akvmDg~lvMPg@	Hard
a_vmDimkvMd@M	Light
mbvmDaemvMPL	Light
qywmDushvMe@]	Light
azymDiqdvMCa@	Light
mepmDqwdvMQ[Em@	Light
gtumDicevMBm@	Light
{tumDwgevML^Zd@	Hard
gfxmDwvivMi@jA	Hard
{kpmD}qzuM]C	Light
qipmD}ywuMPk@	Light
qepmDoywuMQl@	Light
kgpmDuuyuMSC	Light
{`nmDkyvuM]rA	Light
uhvmDowjvMoF|K	Light
gpumDan|vMyA`@wA^	Light
yuumD_l|vMyAb@	Hard
e~tmDau|vM}A`@	Light
oftmDsgvvMnAq@	Light
chtmDqfvvMr@a@	Hard
grsmDmlwvMUl@	Light
}rsmD_kwvMYv@	Hard
etsmDgiwvMXw@	Light
kosmD{r{vMj@xJ	Light
ersmD{~{vMDX^nBh@|D	Light
ersmDu_}vM`@Q	Light
cqsmDg`}vMzAcB	Hard
gnsmDkc}vM{AbB	Light
c{smDoq|vMB]	Hard
{{smD{o|vMVs@	Light
kwqmDkxzvMRR	Hard
adqmDky}vM}CbC	Light
_gqmDmw}vMvAgA	Hard
orrmDiq|vMKBc@X	Light
yzsmDwr|vMdB}C	Light
yusmDcy|vMU^QOT_@	Hard
awsmDsx|vMT_@	Light
kunmDk|wvMe@iBW}@	Hard
iwnmDsaxvMKY	Light
wvnmD}axvMX|@	Light
_nsmDag{vMZpE	Light
axqmDaxzvM[U	Hard
shvmDidsvM_Ar@kAf@	Light
eqvmDiasvMz@GjA[	Light
o`tmD_`uvMTi@`Am@d@_B	Light
{gvmDye|vMJH^E	Hard
u~wmDqtzvMJlF	Light
edzmDceyvMvBpC	Light
m`zmDq`yvMz@nA	Hard
}uzmDatyvMw@c@	Hard
wy{mDk`yvMjB~B	Light
{fzmDmhyvMfArA	Light
un{mDwcxvMMkACO	Hard
cxzmDouyvMsB{@	Light
uh|mDivzvMvDH	Hard
om{mDw~wvMe@_D	Light
c|umDej|vMVE	Hard
c|umDej|vMVEXD	Light
gzwmDknzvMiBp@	Light
o}wmDcp{vM^EvB]	Light
q~ymDa~xvMJP	Light
witmDoevvMr@a@	Hard
s~wmDk|yvM]lA	Hard
ujvmD}c|vMF]Z_@t@@	Light
_cvmDkifvM?t@~@zC	Light
ifvmDihfvMm@TcA`B	Hard
ozwmD}revMqApC	Light
ak|mDuszuMS`@	Light
aarmDa_lvMbAe@NI	Hard
m~qmDq`lvM`@y@D[	Light
w_xmDoyyvMq@~A	Hard
k}wmD_n{vMiAN	Light
oznmDayjvMoCN	Light
o`|mDgilvMjDN	Light
ob{mDellvMmD~BeA`@	Hard
_gomDsvivMfCI	Hard
cpymDcthvMS@iAJ	Hard
ar{mDaglvM{@G	Hard
mv{mDsglvMkCM	Hard
_yqmDk~dvMV`@Dh@	Light
obomDexjvMYP[`@	Light
y}wmDgejvMiAzB	Light
u{wmD_jjvMpAkC	Light
wiymDyfjvMc@|@	Light
{jymD{djvMc@dA	Hard
{xumDyvdvMSm@	Light
s{umDa{hvM_CG	Hard
s_vmDi{hvMu@A	Light
_bumDojhvMTg@Zm@	Light
qbxmD_}ivMsAnC	Light
kdqmD{{jvMq@sA	Light
agqmDe`kvMGO	Hard
k~xmDm_`vMuA[	Hard
mbymDob`vM_@V	Light
qlymD}s_vMjD{G	Hard
cdymDyg`vM@S	Light
mzxmDaifvMgA`CQb@	Light
c{xmDackvM]~@	Light
mcvmDsehvMQNe@~@	Hard
{bvmDiahvMSK	Hard
oatmDoikvM^q@	Hard
}uomD_i~uMHT`AbCp@tB	Light
i`zmDo~tuMb@x@	Hard
adxmDcpgvMcBhD	Hard
ydvmDc|hvMzAB	Hard
ydvmDc|hvM|@[^c@	Light
kapmDyrfvMeBxB	Light
cnwmDaefvMWT	Light
czzmDcwyvMx@Z	Light
mlsmDmxzvMEk@	Light
scqmDeoavM[`Ao@j@[h@E`@|@jDFdA	Light
mupmDcubvMB[LQ	Hard
gcrmD_ubvMNP	Light
skwmD_uzvMa@J	Hard
}ztmD}wlvMVkA	Light
opwmD{_cvMa@D[SGO	Light
{gymDcxevMGd@OP	Hard
shymDkvevMKFc@@	Light
czymDcsdvMRq@ZSX?	Hard
ywymDiudvMZP	Light
enymD_ievMcAbC	Light
mcqmDepavMNU	Hard
}bqmD{pavMJU	Light
qbqmDqqavMPa@	Hard
qoomDqvlvM}@oB}@aA	Light
cfpmDgvfvMVr@LN\fA	Hard
_ppmD}xhvMg@Iy@AHQFo@[YsAqA	Hard
kqpmDizhvMc@a@	Hard
moymD}shvMUERG	Hard
azumDa~lvMQv@	Light
szwmDuibvMl@yA	Light
sz{mDs{evMqBTk@H	Hard
kkymD}thvMlEi@N@JC	Hard
kwzmDm}mvM}@Z	Light
e|zmDm_nvMBVPN|@\	Hard
}wzmD_~mvMfBw@	Light
}vzmDsulvMbAq@	Hard
o|rmDcpkvMV@	Light
outmDq_gvMK?{AcA_@W	Light
wytmDmbgvM[U	Hard
sc{mDk|cvMVm@	Light
qcrmDstbvMwA}AoMaLq@y@qBkD]Qc@G	Light
ei|mDqilvMfAA	Hard
a~xmDw`lvMFi@	Light
y}xmDablvM@W	Hard
alsmDarsuM~HgPvC_H	Light
wczmD}d|vMbCj@	Hard
ezymDkrdvM@W	Light
g_smD_pgvMRA	Hard
_|zmDubfvMt@I	Light
ucsmDy_yuMaAh@sDlC_DnB	Light
kjwmDgxwuMi@t@	Hard
}lzmDatvuMpGkB	Light
mdumDynlvMhCfB	Hard
}uqmD{zivMLQXK	Light
avqmDe|ivMmBsA	Light
okymD{_uvMZpL	Light
knvmDmpsvMGi@i@iBaBsC	Hard
_svmDuysvMeCgE	Hard
_uymD_jxvMz@u@	Light
mnymDy}vvM?R?X	Light
_uymD_jxvMd@FH^GV	Light
ib{mDagwvMeB\	Hard
oe{mDcfwvMqAV	Light
gkwmDm_uvMvC`F	Light
gbxmDcdvvMrA~C	Hard
_qymDkjxvMg@aA	Hard
s_xmDc_vvM|@rBJP	Hard
{dymDi}wvMrHnK	Light
alymDg`uvMNI	Light
ckymDirtvMI}B	Light
_uymDqqxvMPR~@rA	Light
gi{mDihwvMQqA	Hard
_j{mD{kwvMi@yE	Light
_{smD{l|vMN@	Hard
o|tmDcqlvMc@vB	Hard
sl|mDogzuMjAdC	Light
ecwmD_o~vMm@_C	Light
u|mmDuv_vMsEtB	Light
q~xmD_}kvMZkB	Hard
uftmD_{tvMOF	Light
gvymDsvgvMo@rC	Light
kv{mDk|xvMv@tA	Hard
w|ymDqb|vM\@ZK	Hard
_anmDi|pvMYf@}AtA{ChA	Light
q}wmDylzvMWH	Hard
wuwmDsmuvMaC_EkBgD	Light
}`{mDogwvMk@L	Light
wusmDig|vM{CcD	Light
_usmDez|vMW`@	Light
{mymD}prvMDqEKaB	Hard
{jnmDuupvMy@P	Light
wlymDa`mvMtFK	Hard
{|rmDovhvMH@RTA\	Light
q~umDci|vMd@S	Light
g`nmD_ucvMYIKM	Light
ylpmDarzuMq@Q	Hard
ymsmD_qruMNR	Hard
cksmDwa}vMo@[s@W	Hard
gnsmDkc}vMr@V	Hard
gysmD{p|vMi@e@	Light
oyomDobyvMi@a@	Light
e}wmD_dbvMMX[p@m@nA	Light
s}xmD_l`vMVe@	Light
ozwmDeibvMUh@	Light
{rymDqncvMEq@	Light
i`|mDoqyuM~@tB	Light
c}wmD}bwuM~AJ	Light
{{umDgouuMrC|B	Light
}rqmD_|avMqCqGqDoG}D_F	Light
kxqmDsfbvMd@z@	Light
o_|mDcxvuMqAiA	Hard
cozmDw_vuM`A`DTv@	Light
e|ymDyyfvMCZ	Hard
}`ymDglkvM{AgA	Hard
}{xmDohkvMc@W	Light
}p{mDicwvM|Dy@	Light
}xymDocxvMiDrCk@H	Light
eqymDehxvMi@]	Light
mkymDgvtvMSkH	Hard
{vxmDitrvMYB	Light
kxnmDwexvMf@~A	Light
ysomDipwvMRRD`@	Light
a|smD_duvMr@o@~BkA^S	Light
q|smDweuvMFy@He@	Light
qcvmDwdmvMs@O	Light
slvmDib{vMiCz@	Light
}nymDiwbvMDb@	Light
ioymD_vbvMEk@	Hard
asymDoscvMTxC	Hard
wtymDe{dvMo@pB	Hard
gvymDswdvMUzA	Light
_rymDqpdvMyAUo@A	Hard
g{zmD}jdvMd@{@	Light
qd{mD}ycvM_@~@	Light
_y{mD_xdvM[v@GNa@dA	Hard
i|{mDiqdvMSf@	Light
i}nmDippvMHC	Hard
q~vmDudfvM`@@	Hard
k_vmDuwfvMlAgC	Light
}lumDwvgvMOXAp@	Light
}evmDifdvMTSTC	Hard
}uumDe_evM~@kB	Hard
{tumDwgevMNLp@Fr@[	Light
gqwmDolhvM{@]	Light
eyumDczivM[N	Light
abvmDiyhvMCW_@o@	Light
ggvmDm~ivMPVX`@	Hard
ijvmDmbjvMLNb@l@	Light
whvmDo`jvMPV	Hard
_lvmDmdjvMt@~@	Light
cjvmDuajvMW[	Hard
ckvmD}bjvMY]	Light
ayvmD_eivM\lCFr@	Light
oxwmDsjivM^a@|A}ARO	Light
wywmDghivMEY]i@{B{A	Light
e}xmDycjvMs@g@QM	Light
_|xmDuwhvMw@B	Light
gsxmDecmvMeCb@	Hard
{vxmDw{lvM?l@	Hard
mwxmDabmvMNdC	Light
_lymDubjvM]v@c@fA	Light
odymD_{evMk@d@	Light
mc{mDkllvMjBmA	Hard
k|umDuslvMPqF	Hard
y{umDg{lvMD_@	Light
awumD_amvMeA`@Q`@	Light
yevmD}emvMVB	Light
ozumDcnkvMYn@	Light
_lvmDionvM]f@	Light
exsmDi{kvMBk@OkAM_@	Light
}{smD_~lvMqCC	Hard
evtmDaxhvMKb@]b@	Light
}ztmDo|hvMHG	Hard
sztmDw|hvMl@I	Light
gdtmDuwhvMCPOLO@MEKSAM	Hard
{humDw{ivMQg@	Light
amumDgajvMf@Y	Hard
_fumDeejvMm@X	Light
uetmDk{ivMl@qA	Light
uaqmDkravMUj@	Light
irpmDcubvMCT	Light
}kpmDujcvMd@NNX@`@KZ	Light
wkqmDo{cvM^G	Light
impmDgfgvM_@]	Light
iopmD_kgvM`@`@	Light
oopmDuhgvM@MDILKPCVJHR@RGPIJSDSCQY?Q	Light
icsmDangvMd@Bh@Q	Light
_wqmDymgvMd@@	Light
wmsmDsyfvM@eA	Light
oxqmDszdvMWV	Light
c_smDmuhvMf@I	Light
{dumDmmgvMN[	Light
qqtmDg_gvMXP	Hard
ymtmDqpgvM`AD	Hard
sjtmD_xgvMRq@	Hard
_jtmDqygvM\KhAK	Light
attmD}|fvMDk@	Light
cepmDk{dvM^E	Hard
u_vmD}~gvM}@q@	Light
qnvmDcfjvMg@Y	Light
wuvmDkrlvMUAs@A	Light
o_{mDc_}uMXg@	Light
u~zmDk`}uMf@cA	Hard
qvzmD{l}uMEH[n@	Light
m_{mDulzuMcBkA	Light
_rvmDizxuM|EvB	Light
sdymDub`vMJuA	Light
mprmD}pyuM|@o@	Light
{gpmDymxuM?Y?Y	Hard
}jpmD{pivMi@gB	Light
eymmDa|ivM}BP	Light
}dnmDq|jvMnBU	Light
qvnmDqfnvMeCbA[R	Light
{iqmD}|jvMZaA	Hard
m{rmD}nkvMEP	Light
c`qmDwnhvM]?	Light
ubomDssgvMfFI	Hard
idnmDmzzuMrErE	Light
}bpmDibpvM{@PqDCiBU{@]m@e@	Light
ysvmDmh}vMNn@b@rB	Light
kuvmDmm}vM`@jBNr@	Hard
elpmDqamvMVO	Hard
auymDwvivMc@D	Light
_xnmDqf_vM|A}@	Hard
clqmDahxuMPk@	Hard
wtzmDsivuMWm@	Hard
csymDukxvMZW	Hard
w}xmDqwhvM_@D	Light
e_ymDiwhvMuBV	Light
qowmDc~jvMMI	Hard
o`tmDc~lvMa@Ac@A	Light
s~ymDclfvMYlC	Light
i|ymD}xfvMWbC	Light
{bymDqvhvMUD	Hard
{bymDqvhvMxBW	Light
qvzmDsvlvMHYLaA	Hard
w~mmDw_qvMgAlB	Light
osqmDsovvM`Bo@	Light
yysmDyalvMXv@L^b@j@h@`@	Light
gzsmDkz|vMv@\	Light
gzvmDq_~vMk@z@	Light
mznmDcenvM\O	Light
s{nmDycnvMs@`@	Hard
ocymD}okvM`AqCF[	Light
}symDa}dvMYz@	Hard
{uzmDuzlvMXt@	Hard
o|umDk|gvMTL	Light
u_vmD}~gvMdBpA	Hard
_dumD{r|vMzAc@	Light
kwrmDur|vMjBhA	Hard
qh{mDmgzvMKJ	Hard
s_wmDe_evMuAtC	Light
cmxmDwvhvMdAD	Light
_cqmDiwhvMRp@	Light
uzsmDw~ivMdBB	Light
urfnDc{vvMr@URI	Light
aqfnDy{vvMbAc@	Light
cvenDi~vvMu@@	Light
omfnDy|vvMg@JaA`@YJ]J	Light
qrfnDszvvMsBn@	Hard
qwfnDeyvvMd@M	Light
kvfnDsyvvMx@W	Hard
w_inDuqvvMlAE	Hard
ywenDg~vvMiDF	Light
yvfnD{xvvMyBn@c@L	Light
{tenD{~vvM~AA	Hard
woinDuk_wMNSXH	Light
